#!/usr/bin/env python3
"""Generate all_locales_l10n_test.dart from the AppLocalizations base class."""
import re, textwrap

BASE = "lib/l10n/app_localizations.dart"

# Locale code → class name mapping
LOCALES = [
    ("ar", "AppLocalizationsAr"),
    ("bn", "AppLocalizationsBn"),
    ("de", "AppLocalizationsDe"),
    ("en", "AppLocalizationsEn"),
    ("es", "AppLocalizationsEs"),
    ("fa", "AppLocalizationsFa"),
    ("fr", "AppLocalizationsFr"),
    ("gu", "AppLocalizationsGu"),
    ("he", "AppLocalizationsHe"),
    ("hi", "AppLocalizationsHi"),
    ("it", "AppLocalizationsIt"),
    ("ja", "AppLocalizationsJa"),
    ("kn", "AppLocalizationsKn"),
    ("ko", "AppLocalizationsKo"),
    ("ml", "AppLocalizationsMl"),
    ("mr", "AppLocalizationsMr"),
    ("nl", "AppLocalizationsNl"),
    ("or", "AppLocalizationsOr"),
    ("pa", "AppLocalizationsPa"),
    ("pl", "AppLocalizationsPl"),
    ("pt", "AppLocalizationsPt"),
    ("ru", "AppLocalizationsRu"),
    ("ta", "AppLocalizationsTa"),
    ("te", "AppLocalizationsTe"),
    ("ur", "AppLocalizationsUr"),
    ("zh", "AppLocalizationsZh"),
    ("zh_TW", "AppLocalizationsZhTw"),
]

# Parse keys from the base class
simple_keys = []
param_keys = []

with open(BASE) as f:
    for line in f:
        line = line.strip()
        m = re.match(r"String get (\w+);", line)
        if m:
            simple_keys.append(m.group(1))
            continue
        m = re.match(r"String (\w+)\((.+)\);", line)
        if m:
            name = m.group(1)
            params_raw = m.group(2)
            params = []
            for p in params_raw.split(","):
                p = p.strip()
                parts = p.split()
                if len(parts) == 2:
                    ptype, pname = parts
                    params.append((ptype, pname))
            param_keys.append((name, params))

print(f"Found {len(simple_keys)} simple keys, {len(param_keys)} parameterized keys")

# Build imports
imports = []
for code, cls in LOCALES:
    suffix = code.lower().replace("_", "")
    # zh_TW is in the zh file
    if code == "zh_TW":
        continue  # imported via zh file
    imports.append(f"import 'package:aroundu/l10n/app_localizations_{suffix}.dart';")
# zh includes both zh and zh_TW
imports = sorted(set(imports))

# Generate test
lines = []
lines.append("// AUTO-GENERATED by scripts/gen_l10n_test.py — DO NOT EDIT")
lines.append("// ignore_for_file: lines_longer_than_80_chars")
lines.append("")
lines.append("import 'package:flutter_test/flutter_test.dart';")
for imp in imports:
    lines.append(imp)
lines.append("")
lines.append("void main() {")

total_assertions = 0

for code, cls in LOCALES:
    lines.append(f"  group('Locale: {code}', () {{")
    lines.append(f"    late {cls} l10n;")
    lines.append(f"    setUp(() => l10n = {cls}());")
    lines.append("")

    # Simple keys — batch into groups of ~50 for readability
    batch_size = 50
    for i in range(0, len(simple_keys), batch_size):
        batch = simple_keys[i : i + batch_size]
        start_idx = i + 1
        end_idx = i + len(batch)
        lines.append(f"    test('simple keys {start_idx}–{end_idx} are non-empty', () {{")
        for key in batch:
            lines.append(f"      expect(l10n.{key}, isNotEmpty, reason: '{key}');")
            total_assertions += 1
        lines.append("    });")
        lines.append("")

    # Parameterized keys
    if param_keys:
        lines.append(f"    test('parameterized keys are non-empty', () {{")
        for name, params in param_keys:
            args = []
            for ptype, pname in params:
                if ptype == "String":
                    args.append("'test'")
                elif ptype == "int":
                    args.append("1")
                elif ptype == "double":
                    args.append("1.0")
                else:
                    args.append("'test'")
            call = f"l10n.{name}({', '.join(args)})"
            lines.append(f"      expect({call}, isNotEmpty, reason: '{name}');")
            total_assertions += 1
        lines.append("    });")
        lines.append("")

    lines.append("  });")
    lines.append("")

lines.append("}")

print(f"Total assertions: {total_assertions}")

with open("test/l10n/all_locales_l10n_test.dart", "w") as f:
    f.write("\n".join(lines) + "\n")

print("Generated test/l10n/all_locales_l10n_test.dart")
