#!/usr/bin/env python3
"""
Generates the complete app_en.arb with all new keys,
then batch-updates all 26 locale ARB files.
"""
import json, pathlib, copy

L10N = pathlib.Path(__file__).resolve().parent.parent / "lib" / "l10n"

# ── Complete English ARB ─────────────────────────────────────────────────────
EN = {
  "@@locale": "en",
  "appName": "AroundU",

  # ── Auth ──────────────────────────────────────────────────────────────────
  "loginTitle": "Log In",
  "registerTitle": "Create Account",
  "emailLabel": "Email",
  "passwordLabel": "Password",
  "confirmPasswordLabel": "Confirm Password",
  "forgotPassword": "Forgot Password?",
  "loginButton": "Log In",
  "registerButton": "Sign Up",
  "orContinueWith": "Or continue with",
  "dontHaveAccount": "Don't have an account?",
  "alreadyHaveAccount": "Already have an account?",
  "welcomeBack": "Welcome Back",
  "loginSubtitle": "Sign in to continue as provider or worker.",
  "noAccountYet": "No account yet?",
  "createOne": "Create one",
  "emailRequired": "Email is required",
  "enterValidEmail": "Enter a valid email",
  "passwordRequired": "Password is required",
  "minimumSixCharacters": "Minimum 6 characters",
  "unableToLogin": "Unable to login. Please retry.",
  "fieldRequired": "{field} is required",
  "@fieldRequired": { "placeholders": { "field": { "type": "String" } } },
  "enterValidPhone": "Enter a valid phone number",
  "unableToRegister": "Unable to register",
  "registrationSuccess": "Registration successful. Please log in.",
  "registerSubtitle": "Register as provider or worker with your basic location profile.",
  "roleLabel": "Role",
  "roleJobProvider": "Job Provider",
  "roleJobWorker": "Job Worker",
  "countryLabel": "Country",
  "currencyLabel": "Currency",
  "cityLabel": "City",
  "postalCodeLabel": "Postal code",
  "areaOptionalLabel": "Area (optional)",
  "fullAddressOptionalLabel": "Full address (optional)",
  "alreadyRegistered": "Already registered?",
  "logInLink": "Log in",

  # ── Onboarding ────────────────────────────────────────────────────────────
  "onboardingTitle1": "Book Local Services Fast",
  "onboardingSubtitle1": "Post your requirement in minutes and get matched with nearby verified workers.",
  "onboardingTitle2": "Compare Bids Transparently",
  "onboardingSubtitle2": "Review pricing, profiles, and timelines before assigning your job with confidence.",
  "onboardingTitle3": "Track Every Job Clearly",
  "onboardingSubtitle3": "Stay updated from job creation to completion with role-based dashboards.",
  "getStarted": "Get Started",
  "skip": "Skip",
  "next": "Next",
  "newHereCreateAccount": "New here? Create account",

  # ── Role Selection ────────────────────────────────────────────────────────
  "roleSelectionTitle": "Choose Your Role",
  "roleClient": "Client",
  "roleClientDesc": "I need help with tasks",
  "roleWorker": "Worker",
  "roleWorkerDesc": "I want to offer my skills",
  "continueButton": "Continue",
  "roleSelectionSubtitle": "Select the workflow you want to use in AroundU.",
  "signedInAs": "Signed in as {email}",
  "@signedInAs": { "placeholders": { "email": { "type": "String" } } },
  "roleProviderDesc": "Post jobs and manage incoming bids.",
  "roleWorkerDescAlt": "Browse nearby jobs and place bids quickly.",

  # ── Tabs / Nav ────────────────────────────────────────────────────────────
  "homeTab": "Home",
  "jobsTab": "Jobs",
  "chatTab": "Chat",
  "profileTab": "Profile",
  "providerTabMyTasks": "My Tasks",
  "providerTabPostTask": "Post Task",
  "tasksNavLabel": "Tasks",
  "postNavLabel": "Post",
  "workerTabTaskFeed": "Task Feed",
  "feedNavLabel": "Feed",

  # ── Jobs ──────────────────────────────────────────────────────────────────
  "myJobs": "My Jobs",
  "workerFeed": "Available Jobs",
  "createJob": "Create Job",
  "postJob": "Post a Job",
  "editJob": "Edit Job",
  "deleteJob": "Delete Job",
  "deleteJobConfirm": "Are you sure you want to delete this job?",
  "jobTitle": "Title",
  "jobDescription": "Description",
  "jobCategory": "Category",
  "jobBudget": "Budget",
  "jobLocation": "Location",
  "jobDueDate": "Due Date",
  "jobSkills": "Skills Required",
  "jobUrgency": "Urgency",
  "jobPaymentMode": "Payment Mode",
  "urgencyNormal": "Normal",
  "urgencyMedium": "Medium",
  "urgencyUrgent": "Urgent",
  "urgencyAsap": "ASAP",
  "paymentOffline": "Offline",
  "paymentEscrow": "Escrow",
  "paymentMethod": "Payment Method",
  "payInCash": "Pay in Cash",
  "secureEscrow": "Secure Escrow",

  # ── Filters ───────────────────────────────────────────────────────────────
  "filterAll": "All",
  "filterOpen": "Open",
  "filterActive": "Active",
  "filterInProgress": "In Progress",
  "filterCompleted": "Completed",
  "filterCancelled": "Cancelled",
  "filterExpired": "Expired",
  "filterNearby": "Nearby",
  "filterAllMine": "All Mine",
  "filterBidPlaced": "Bid Placed",
  "filterAccepted": "Accepted",

  # ── Provider empty states ────────────────────────────────────────────────
  "noTasksPostedYet": "No tasks posted yet",
  "noOpenTasks": "No open tasks",
  "noActiveTasks": "No active tasks",
  "noTasksInProgress": "No tasks in progress",
  "noCompletedTasks": "No completed tasks",
  "noCancelledTasks": "No cancelled tasks",
  "noExpiredTasks": "No expired tasks",
  "unableToLoadTasks": "Unable to load tasks",

  # ── Worker empty states ──────────────────────────────────────────────────
  "noNearbyJobs": "No nearby jobs right now",
  "noJobsYetBid": "No jobs yet — place a bid to get started!",
  "noPendingBids": "No pending bids",
  "noAcceptedJobs": "No accepted jobs",
  "noJobsInProgress": "No jobs in progress",
  "noCompletedJobsYet": "No completed jobs yet",
  "noCancelledJobs": "No cancelled jobs",
  "noExpiredJobs": "No expired jobs",
  "pullDownToRefreshCheck": "Pull down to refresh and check again.",
  "unableToLoadJobs": "Unable to load jobs",

  # ── Post Task form ──────────────────────────────────────────────────────
  "postNewTask": "Post a New Task",
  "postTaskSubtitle": "Add clear details so workers can send accurate offers.",
  "taskTitleLabel": "Task title",
  "savingLocation": "Saving location…",
  "tapToSelectLocation": "Tap to select location",
  "postTaskButton": "Post Task",
  "addSkillWarning": "Add at least one required skill for this task",
  "enterValidBudget": "Enter a valid budget amount",
  "setJobLocationWarning": "Please set a job location before posting",
  "jobPostedSuccess": "Job posted successfully",
  "failedToPostJob": "Failed to post job. Please retry.",
  "failedToSaveLocation": "Failed to save location",
  "unableToLoadJobWorkflow": "Unable to load job workflow",
  "unknownError": "Unknown error",

  # ── Job statuses ─────────────────────────────────────────────────────────
  "statusOpenForBids": "Open for Bids",
  "statusInProgress": "In Progress",
  "statusCompleted": "Completed",
  "statusCancelled": "Cancelled",
  "statusPendingStart": "Pending Start",
  "statusPendingRelease": "Pending Release",

  # ── Bids/Offers ──────────────────────────────────────────────────────────
  "bids": "Bids",
  "noBids": "No bids yet",
  "placeBid": "Place Bid",
  "bidAmount": "Bid Amount",
  "bidNotes": "Notes (optional)",
  "yourBid": "Your Bid",
  "acceptBid": "Accept Bid",
  "rejectBid": "Reject Bid",
  "bidAccepted": "Bid Accepted",
  "bidRejected": "Bid Rejected",
  "bidPending": "Pending",
  "offersSection": "Offers",
  "noOffersReceivedYet": "No offers received yet.",
  "offerAccepted": "Offer Accepted",
  "offerRejected": "Offer Rejected",
  "offerPending": "Offer Pending",
  "workerNumber": "Worker #{id}",
  "@workerNumber": { "placeholders": { "id": { "type": "int" } } },
  "acceptThisOffer": "Accept this Offer",
  "messageWorker": "Message Worker",
  "offerAcceptedSnack": "Offer accepted",
  "yourOffer": "Your Offer",
  "bidStatusSelected": "Selected",
  "bidStatusRejected": "Rejected",
  "bidStatusPending": "Pending",
  "placeYourOffer": "Place Your Offer",
  "yourOfferAmount": "Your offer amount",
  "messageToClientOptional": "Message to client (optional)",
  "addPartnerOptional": "Add a partner (optional)",
  "partnerNameLabel": "Partner name",
  "partnerFeeLabel": "Partner fee",
  "partnerFeeAmount": "+ {symbol}{amount} partner fee",
  "@partnerFeeAmount": { "placeholders": { "symbol": { "type": "String" }, "amount": { "type": "String" } } },
  "submitOffer": "Submit Offer",
  "enterValidOfferAmount": "Enter a valid offer amount",
  "offerSubmittedSuccess": "Offer submitted successfully",
  "clientSelectedYourOffer": "Client Selected Your Offer!",
  "handshakeHint": "Accept to confirm this job, or decline if you're no longer available.",
  "handshakeAccepted": "Handshake accepted",
  "handshakeDeclined": "Handshake declined",
  "acceptJob": "Accept Job",
  "decline": "Decline",

  # ── Codes & Escrow ──────────────────────────────────────────────────────
  "startCode": "Start Code",
  "releaseCode": "Release Code",
  "generateCodes": "Generate Codes",
  "verifyCode": "Verify Code",
  "enterCode": "Enter Code",
  "generateStartCode": "Generate Start Code",
  "startCodeCopied": "Start code copied",
  "reserveInEscrow": "Reserve {symbol}{amount} in Escrow",
  "@reserveInEscrow": { "placeholders": { "symbol": { "type": "String" }, "amount": { "type": "String" } } },
  "releaseCodeCopied": "Release code copied",
  "releaseCodeHint": "Share this verbally with the worker. They enter it to confirm task completion.",
  "regenerateCode": "Regenerate Code",
  "generateReleaseCode": "Generate Release Code",
  "taskCodesGenerated": "Task codes generated",
  "newReleaseCodeGenerated": "New release code generated",
  "readyToBegin": "Ready to Begin?",
  "startCodeHint": "Ask the client for the start code and enter it below to officially begin work.",
  "verifyAndStartWork": "Verify & Start Work",
  "startCodeVerified": "Start code verified. Task is now in progress.",
  "enterStartCodeFirst": "Enter start code first",
  "workInProgress": "Work In Progress",
  "releaseCodePrompt": "Once done, ask the client for the 6-digit release code.",
  "releaseCodeHelper": "Enter the 6-digit code from the client",
  "confirmWorkCompleted": "Confirm Work Completed",
  "workConfirmedPaymentReleased": "Work confirmed — payment released!",
  "enterReleaseCodeWarning": "Enter the release code from the client",
  "escrow": "Escrow",
  "lockEscrow": "Lock Escrow",
  "releaseEscrow": "Release Payment",
  "paymentLocked": "Payment Locked",
  "paymentReleased": "Payment Released",
  "paymentSafelyReserved": "Payment safely reserved",

  # ── Task actions ─────────────────────────────────────────────────────────
  "cancelTask": "Cancel Task",
  "taskCancelled": "Task cancelled",
  "deleteTask": "Delete Task",
  "deleteTaskTitle": "Delete task?",
  "deleteTaskConfirm": "This will remove the task and all associated offers.",
  "taskDeleted": "Task deleted",
  "typeFirstMessage": "Type your first message…",
  "send": "Send",
  "failedToSendMessage": "Failed to send message",

  # ── Chat ──────────────────────────────────────────────────────────────────
  "conversations": "Messages",
  "noMessagesYet": "No messages yet",
  "noMessagesSubtitle": "Your conversations will appear here when you start chatting about a task.",
  "startConversation": "Start the conversation!",
  "typeMessage": "Type a message...",
  "typing": "typing...",
  "newMessages": "New Messages",
  "now": "now",
  "minutesAgo": "{count}m ago",
  "@minutesAgo": { "placeholders": { "count": { "type": "int" } } },
  "workersCount": "{count, plural, =1{1 worker} other{{count} workers}}",
  "@workersCount": { "placeholders": { "count": { "type": "int" } } },
  "chatToday": "Today",
  "chatYesterday": "Yesterday",
  "chatYouPrefix": "You: {message}",
  "@chatYouPrefix": { "placeholders": { "message": { "type": "String" } } },
  "chatReFallback": "Re: {jobTitle}",
  "@chatReFallback": { "placeholders": { "jobTitle": { "type": "String" } } },
  "noConversationsYet": "No conversations yet",
  "loadingConversations": "Loading conversations...",
  "loadingMessages": "Loading messages...",

  # ── Profile ──────────────────────────────────────────────────────────────
  "profile": "Profile",
  "editProfile": "Edit Profile",
  "fullName": "Full Name",
  "phone": "Phone Number",
  "bio": "Bio",
  "skills": "Skills",
  "saveChanges": "Save Changes",
  "logout": "Log Out",
  "logoutConfirm": "Are you sure you want to log out?",
  "myProfile": "My Profile",
  "unknown": "Unknown",
  "experienceLabel": "Experience",
  "statusLabel": "Status",
  "notSet": "Not set",
  "onDuty": "On Duty",
  "offDuty": "Off Duty",
  "yearsCount": "{count} years",
  "@yearsCount": { "placeholders": { "count": { "type": "int" } } },
  "themeAndColors": "Theme & Colors",
  "aiModelLabel": "AI Model",
  "availableForWork": "Available for Work",
  "visibleToClients": "You are visible to clients",
  "currentlyOffDuty": "You are currently off duty",
  "myReviews": "My Reviews",
  "deleteAccount": "Delete Account",
  "deleteAccountConfirm": "This will permanently delete your account and all data. This cannot be undone.",
  "couldNotDeleteAccount": "Could not delete account",
  "profilePhotoUpdated": "Profile photo updated",
  "profileUpdated": "Profile updated",
  "nameLabel": "Name",
  "profileImageUrl": "Profile Image URL",
  "yearsOfExperience": "Years of Experience",
  "certificationsLabel": "Certifications",
  "payoutAccountLabel": "Payout Account",
  "onDutySubtitle": "Toggle availability for new tasks",
  "loadingProfile": "Loading profile...",
  "availabilityLabel": "Availability",
  "memberLabel": "Member",
  "available": "Available",
  "unavailable": "Unavailable",
  "viewAllReviews": "View All Reviews",

  # ── Settings / Appearance / Language ─────────────────────────────────────
  "settings": "Settings",
  "appearance": "Appearance",
  "language": "Language",
  "darkMode": "Dark Mode",
  "lightMode": "Light Mode",
  "systemMode": "System",
  "accentColour": "Accent Colour",
  "customColour": "Custom",
  "preview": "Preview",
  "previewTitle": "Your colours look great!",
  "previewSubtitle": "This is how your app will look.",
  "primary": "Primary",
  "secondary": "Secondary",
  "modeLabel": "Mode",
  "pickAColour": "Pick a colour",
  "systemDefault": "System default",
  "darkModeSubtitle": "Switch between light and dark themes",

  # ── Reviews ──────────────────────────────────────────────────────────────
  "reviews": "Reviews",
  "leaveReview": "Leave a Review",
  "noReviews": "No reviews yet",
  "rating": "Rating",
  "reviewComment": "Comment",
  "submitReview": "Submit Review",
  "howWasWorker": "How was {name}?",
  "@howWasWorker": { "placeholders": { "name": { "type": "String" } } },
  "feedbackHelps": "Your feedback helps the community",
  "thanksForReview": "Thanks for your review!",
  "shareExperienceHint": "Share your experience (optional)",
  "ratingExcellent": "Excellent!",
  "ratingGreat": "Great!",
  "ratingGood": "Good",
  "ratingFair": "Fair",
  "ratingPoor": "Poor",
  "tapToRate": "Tap to rate",
  "workerReviewsTitle": "{name}'s Reviews",
  "@workerReviewsTitle": { "placeholders": { "name": { "type": "String" } } },
  "loadingReviews": "Loading reviews...",
  "noReviewsSubtitle": "Reviews will appear here after completed tasks.",
  "allReviews": "All Reviews",
  "reviewCount": "{count, plural, =1{1 review} other{{count} reviews}}",
  "@reviewCount": { "placeholders": { "count": { "type": "int" } } },
  "anonymous": "Anonymous",

  # ── Common UI ────────────────────────────────────────────────────────────
  "loading": "Loading...",
  "error": "Something went wrong",
  "retry": "Retry",
  "tryAgain": "Try Again",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "delete": "Delete",
  "save": "Save",
  "edit": "Edit",
  "close": "Close",
  "search": "Search",
  "noResults": "No results found",
  "pullToRefresh": "Pull to refresh",
  "pullDownToRefresh": "Pull down to refresh.",
  "yes": "Yes",
  "required": "Required",
  "stop": "Stop",
  "clear": "Clear",
  "send": "Send",

  # ── AI ────────────────────────────────────────────────────────────────────
  "aiSetup": "AI Setup",
  "aiAnalysis": "AI Analysis",
  "unlockAi": "Unlock AI Analysis",
  "aiTagline": "On-Device  ·  Private  ·  Free",
  "deviceCheck": "Device Check",
  "chooseModel": "Choose Your Model",
  "chooseModelSubtitle": "Download one or more models. You can switch between them later.",
  "initializingAi": "Initializing AI runtime…",
  "modelStorage": "Model Storage",
  "deviceIncompatible": "On-device AI requires a physical device with GPU support. Simulators and emulators are not compatible.",
  "enhanceDescription": "Enhance",
  "bidInsights": "Bid Insights",
  "whyThisJob": "Why this?",
  "suggestPrice": "Suggest Price",
  "analyzing": "Analyzing…",
  "aiCapabilities": "AI Capabilities",
  "onDeviceAi": "On-Device AI",
  "aiTaglineSetup": "Private · Offline · Free",
  "aiSetupDescription": "Get smart suggestions for tasks and bids powered by an AI model that runs entirely on your device. No data leaves your phone.",
  "physicalDevice": "Physical device",
  "emulatorDetected": "Emulator detected",
  "ram": "RAM",
  "sufficient": "Sufficient",
  "freeStorage": "Free storage",
  "mbFree": "{mb} MB free",
  "@mbFree": { "placeholders": { "mb": { "type": "int" } } },
  "aiRequiresPhysicalDevice": "AI features require a physical device.",
  "multilingual": "Multilingual",
  "downloadingProgress": "Downloading… {percent}%",
  "@downloadingProgress": { "placeholders": { "percent": { "type": "String" } } },
  "loadingModel": "Loading model…",
  "retryDownload": "Retry Download",
  "activeAndReady": "Active & Ready",
  "remove": "Remove",
  "enableAi": "Enable AI",
  "downloadAiModel": "Download AI Model",
  "deviceNotSupported": "Device not supported",
  "downloadBackgroundNote": "Download happens in the background — you can leave this screen. The model file will be stored on your device and can be removed at any time.",
  "removeAiModelTitle": "Remove AI Model?",
  "removeAiModelConfirm": "This will delete the AI model from your device. You can re-download it later.",
  "analyzeWithAi": "Analyze with AI",
  "aiAssistantAvailable": "AI Assistant available",
  "aiSetupPrompt": "Set up an on-device AI model to get smart suggestions.",
  "setup": "Setup",

  # ── Admin ─────────────────────────────────────────────────────────────────
  "adminDashboard": "Admin Dashboard",
  "failedToLoadDashboard": "Failed to load dashboard",
  "platformOverview": "Platform Overview",
  "liveStatistics": "Live statistics from the backend.",
  "usersSection": "Users",
  "adminTabClients": "Clients",
  "adminTabWorkers": "Workers",
  "adminTabAccount": "Account",
  "jobsSection": "Jobs",
  "activeLabel": "Active",
  "todaySection": "Today",
  "createdLabel": "Created",
  "completedLabel": "Completed",
  "deleteUserTitle": "Delete {role}",
  "@deleteUserTitle": { "placeholders": { "role": { "type": "String" } } },
  "deleteUserConfirm": "This action removes {name} ({email}) permanently. Continue?",
  "@deleteUserConfirm": { "placeholders": { "name": { "type": "String" }, "email": { "type": "String" } } },
  "userDeletedSuccess": "User deleted successfully",
  "unableToLoadUsers": "Unable to load users",
  "noClientsFound": "No clients found",
  "noWorkersFound": "No workers found",
  "deleteUserTooltip": "Delete user",
  "adminSession": "Admin Session",
  "adminManageUsersHint": "Manage users from the Clients and Workers tabs.",

  # ── Worker Shell ──────────────────────────────────────────────────────────
  "distanceKm": "{radius} km",
  "@distanceKm": { "placeholders": { "radius": { "type": "int" } } },
  "youreOffline": "You're Offline",
  "offlineHint": "Toggle the switch in the top bar to go online and discover nearby jobs.",
  "yourSkills": "Your Skills",
  "skillsSubtitle": "Search and add skills. These are sent to the server to filter your job feed.",
  "addSkillLabel": "Add Skill",
  "typeToSearchSkills": "Type to search skills…",
  "savedSkillsCount": "Saved Skills ({count})",
  "@savedSkillsCount": { "placeholders": { "count": { "type": "int" } } },
  "noSkillsAdded": "No skills added yet. Search above to add relevant skills.",
  "unableToLoadTaskDetails": "Unable to load task details",
  "detailDistance": "Distance",

  # ── Location Picker ──────────────────────────────────────────────────────
  "chooseLocation": "Choose Location",
  "savedTab": "Saved",
  "pinOnMapTab": "Pin on Map",
  "locationDeniedPermanently": "Location permanently denied. Enable it in Settings.",
  "couldNotGetLocation": "Could not get location",
  "searchPlaces": "Search places…",
  "switchToSatellite": "Switch to Satellite",
  "switchToRoadMap": "Switch to Road map",
  "goToMyLocation": "Go to my location",
  "confirmLocation": "Confirm Location",
  "useWithoutSaving": "Use without saving",
  "saveAndUse": "Save & use",
  "useMyCurrentLocation": "Use my current location",
  "detectingLocation": "Detecting location…",
  "saveAddress": "Save Address",
  "saveAddressSubtitle": "Add a label and recipient details for this location.",
  "labelField": "Label",
  "labelHome": "Home",
  "labelWork": "Work",
  "labelOther": "Other",
  "recipientName": "Recipient Name",
  "recipientNameHint": "e.g. Rahul Sharma",
  "recipientPhone": "Recipient Phone",
  "recipientPhoneHint": "e.g. 9876543210",
  "pickFromContacts": "Pick from contacts",
  "contactsAccessDenied": "Contacts access denied — name was copied. Please enter the phone number manually.",
  "openSettings": "Open Settings",
  "couldNotOpenContacts": "Could not open contacts",
  "areaNeighbourhood": "Area / Neighbourhood",
  "areaHint": "e.g. Koramangala",
  "cityHint": "e.g. Bengaluru",
  "postalCodeRequired": "Postal Code",
  "postalCodeHint": "e.g. 560034",
  "countryCodeRequired": "Country Code",
  "countryCodeHint": "e.g. IN",

  # ── Skill Field ──────────────────────────────────────────────────────────
  "requiredSkillsLabel": "Required Skills",
  "skillHintText": "e.g. plumbing, painting…",
  "skillHelperEmpty": "Type skills and separate them with commas",
  "skillsAddedCount": "{count, plural, =1{1 skill added} other{{count} skills added}}",
  "@skillsAddedCount": { "placeholders": { "count": { "type": "int" } } },

  # ── Languages ────────────────────────────────────────────────────────────
  "languagePicker": "Select Language",
  "languageEnglish": "English",
  "languageHindi": "हिन्दी",
  "languageTamil": "தமிழ்",
  "languageTelugu": "తెలుగు",
  "languageKannada": "ಕನ್ನಡ",
  "languageMalayalam": "മലയാളം",
  "languageBengali": "বাংলা",
  "languageGujarati": "ગુજરાતી",
  "languageMarathi": "मराठी",
  "languagePunjabi": "ਪੰਜਾਬੀ",
  "languageOdia": "ଓଡ଼ିଆ",
  "languageUrdu": "اردو",
  "languageSpanish": "Español",
  "languageGerman": "Deutsch",
  "languageFrench": "Français",
  "languagePortuguese": "Português",
  "languageItalian": "Italiano",
  "languageDutch": "Nederlands",
  "languagePolish": "Polski",
  "languageRussian": "Русский",
  "languageJapanese": "日本語",
  "languageKorean": "한국어",
  "languageChineseSimplified": "简体中文",
  "languageChineseTraditional": "繁體中文",
  "languageArabic": "العربية",
  "languagePersian": "فارسی",
  "languageHebrew": "עברית",

  # ── Accent Color Labels ──────────────────────────────────────────────────
  "accentColorBlue": "Blue",
  "accentColorYellow": "Yellow",
  "accentColorGreen": "Green",
  "accentColorPink": "Pink",
  "accentColorRed": "Red",
  "accentColorPurple": "Purple",
  "accentColorOrange": "Orange",
  "accentColorTeal": "Teal",
  "accentColorCustom": "Custom",

  # ── Payment Status Banner ────────────────────────────────────────────────
  "paymentStatusPending": "Payment pending",
  "paymentStatusLocked": "Money is safely reserved",
  "paymentStatusReleased": "Payment released successfully",
  "paymentStatusOffline": "Pay directly upon completion",
  "paymentStatusGeneric": "Payment status: {status}",
  "@paymentStatusGeneric": { "placeholders": { "status": { "type": "String" } } },

  # ── Job Status Labels ────────────────────────────────────────────────────
  "jobStatusOpenForOffers": "Open For Offers",
  "jobStatusOfferAccepted": "Offer Accepted",
  "jobStatusReadyToStart": "Ready to Start",
  "jobStatusInProgress": "In Progress",
  "jobStatusPendingPayment": "Pending Payment",
  "jobStatusPaymentReleased": "Payment Released",
  "jobStatusTaskCompleted": "Task Completed",
  "jobStatusCancelled": "Cancelled",

  # ── Detail Labels / Tooltips ─────────────────────────────────────────────
  "detailBudgetLabel": "Budget",
  "detailLocationLabel": "Location",
  "detailSkillsLabel": "Skills",
  "detailJobIdLabel": "Job ID",
  "tooltipCopy": "Copy",
  "tooltipDeleteAddress": "Delete address",
  "confirmDeleteAddress": "Remove \"{addressLabel}\" from saved addresses?",
  "@confirmDeleteAddress": { "placeholders": { "addressLabel": { "type": "String" } } },

  # ── Error Messages ───────────────────────────────────────────────────────
  "errorNotAuthenticated": "Not authenticated. Please log in again.",
  "errorCouldNotOpenImagePicker": "Could not open image picker.",
  "errorCouldNotReadImage": "Could not read the selected image.",
  "errorImageTooLarge": "Image must be under 5 MB. Please choose a smaller file.",
  "errorUploadFailed": "Upload failed. Please try again.",
  "errorNameRequired": "Name is required",
  "errorRatingRequired": "Please select a rating",
  "errorNotLoggedIn": "Please log in first",
  "errorAdminProfileUpdateNotSupported": "Admin profile updates are not supported in this flow",
  "errorAdminDeletionDisabled": "Admin account deletion is disabled in mobile flow",

  # ── Network / API Errors ─────────────────────────────────────────────────
  "errorConnectionTimeout": "Connection timed out. Check your network and try again.",
  "errorConnectionError": "Unable to connect to the server. Check your network.",
  "errorRequestCancelled": "Request was cancelled.",
  "errorBadRequest": "Invalid request. Please check your input.",
  "errorSessionExpired": "Session expired. Please log in again.",
  "errorPermissionDenied": "You do not have permission to perform this action.",
  "errorResourceNotFound": "Resource not found.",
  "errorConflict": "Conflict: the action cannot be completed in the current state.",
  "errorFileTooLarge": "File too large. Maximum size is 5 MB.",
  "errorValidationError": "Validation error. Please review your input.",
  "errorTooManyRequests": "Too many requests. Please wait and try again.",
  "errorServerError": "Server error. Please try again later.",
  "errorRequestFailed": "Request failed with status {statusCode}",
  "@errorRequestFailed": { "placeholders": { "statusCode": { "type": "String" } } },
  "errorNetworkFailed": "Network request failed.",

  # ── Internal Error Messages ──────────────────────────────────────────────
  "errorNetworkRequestFailed": "Network request failed",
  "errorMalformedSkillResponse": "Malformed skill suggest response",
  "errorMalformedResponse": "Malformed response payload",
  "errorMalformedAdminResponse": "Malformed admin overview response",
  "errorAdminAccessRequired": "Admin access is required",
  "errorDescriptionUnavailable": "Description unavailable",
  "errorUnauthorizedAction": "Only {roleLabel} can perform this action",
  "@errorUnauthorizedAction": { "placeholders": { "roleLabel": { "type": "String" } } },

  # ── AI Job Creation ───────────────────────────────────────────────────────
  "howToCreateTask": "How would you like to create your task?",
  "fillManually": "Fill Manually",
  "describeWithAi": "Describe with AI",
  "aiDescribeProblem": "Describe Your Problem",
  "aiDescribeSheetSubtitle": "Tell us what you need help with in your own words. Our AI will fill in the form for you.",
  "aiDescribeHint": "e.g. My kitchen tap is leaking and I need a plumber to fix it as soon as possible. Budget around 500.",
  "aiDescribeMinCharsWarning": "Please describe your problem in at least 10 characters",
  "aiGenerateForm": "Generate Form",
  "aiParsingJob": "Analysing your description…",
  "aiJobPrefillSuccess": "Form filled from your description. Please review and adjust.",
  "aiJobParseWarning": "Partially filled. Missing: {fields}",
  "@aiJobParseWarning": { "placeholders": { "fields": { "type": "String" } } },
  "aiJobParseFailed": "Could not understand the description. Please try again or fill manually.",
  "aiPrefillBanner": "AI pre-filled. Review and edit before posting.",
  "addImageContext": "Add image for context",
  "imageAttached": "Image attached",

  # ── AI Job Ranking ──────────────────────────────────────────────────────
  "aiTopMatchesSection": "Top Matches",
  "nearbyJobsSection": "Nearby Jobs",
  "aiRankingInProgress": "Finding your best matches…",
  "aiBadge": "AI",

  # ── AI Bid Suggestion ───────────────────────────────────────────────────
  "suggestBidAi": "Suggest Bid (AI)",
  "aiSuggestingBid": "Generating bid suggestion\u2026",
  "aiBidSuggestedSuccess": "Bid pre-filled from AI suggestion. Review before submitting.",
  "aiBidGenerateFailed": "Could not generate a suggestion. Please fill manually.",
  "aiBidSuggestionBanner": "AI suggested. Review and adjust.",

  # ── AI Smart Reply Suggestions ──────────────────────────────────────────
  "aiSuggestReply": "Suggest reply",
  "aiGeneratingReplies": "Generating replies\u2026",
  "aiSmartReplies": "Smart replies",
}


def strip_metadata_keys(d):
    """Return a copy of d with only translatable keys (skip @-prefixed)."""
    return {k: v for k, v in d.items() if not k.startswith("@")}


def translatable_keys(d):
    """Return set of keys that hold translatable strings (not metadata, not @@locale)."""
    return {k for k, v in d.items() if isinstance(v, str) and not k.startswith("@")}


def write_arb(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


# ── Step 1: Write app_en.arb ────────────────────────────────────────────────
en_path = L10N / "app_en.arb"
write_arb(en_path, EN)
print(f"✓ Wrote {en_path}  ({len(translatable_keys(EN))} translatable keys)")


# ── Step 2: Update every locale ARB ─────────────────────────────────────────
en_keys = translatable_keys(EN)

locale_files = sorted(L10N.glob("app_*.arb"))
for lf in locale_files:
    if lf.name == "app_en.arb":
        continue

    with open(lf, encoding="utf-8") as f:
        locale_data = json.load(f)

    existing_keys = translatable_keys(locale_data)
    missing = en_keys - existing_keys

    if not missing:
        print(f"  {lf.name}: already has all keys")
        continue

    # For missing keys, copy English text as placeholder
    for k in sorted(missing):
        locale_data[k] = EN[k]
        # Copy metadata if any
        meta_key = f"@{k}"
        if meta_key in EN:
            locale_data[meta_key] = EN[meta_key]

    # Also remove keys that no longer exist in English
    stale = existing_keys - en_keys - {"@@locale"}
    for k in stale:
        locale_data.pop(k, None)
        locale_data.pop(f"@{k}", None)

    write_arb(lf, locale_data)
    print(f"  {lf.name}: added {len(missing)} keys, removed {len(stale)} stale")


print("\nDone! Run: flutter gen-l10n")
